name: impaktfull_ui_figma_sync_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

dependencies:
  impaktfull_ui_figma_sync:
    path: ../

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

impaktfull_ui_figma_sync:
  figma_file_key: #your_figma_file_key_comes_here
  personal_access_token: #your_personal_access_token_comes_here
