name: impaktfull_ui_figma_sync
description: A dart package to sync figma design variables to flutter/dart
version: 0.0.1
repository: https://github.com/impaktfull/flutter_impaktfull_ui_figma_sync

environment:
  sdk: ^3.1.3

dependencies:
  path: ^1.8.0
  args: ^2.6.0
  yaml: ^3.1.2
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
